#version: "3.9"

services:
  app:
    image: sunakang1/beeve-server-app:prod
    container_name: beeve-server
    depends_on:
      - postgres
      - mongodb
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 512m

  postgres:
    image: postgres:16
    container_name: beeve-postgres
    environment:
      POSTGRES_DB: beeve
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m

  mongodb:
    image: mongo:7
    container_name: beeve-mongo
    environment:
      MONGO_INITDB_DATABASE: beeve
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m

volumes:
  postgres_data:
  mongo_data:
