spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        default_schema: beeve
        format_sql: true
        highlight_sql: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expiration: ${JWT_ACCESS_EXP}
  refresh-expiration: ${JWT_REFRESH_EXP}

logging:
  level:
    org.hibernate.SQL: DEBUG

springdoc:
  swagger-ui:
    doc-expansion: none
    persist-authorization: true
