@base = {{host}}/fitness

### ─────────────────────────────────
### 1) 체력 측정 등록
### ─────────────────────────────────
POST {{base}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "measurePlace": "GYM",
  "wallPushUpReps": 20,
  "stepTestRecoveryBpm": 96,
  "crossCrunchReps": 25,
  "sitAndReach": 20.0,
  "reactionTime": 0.45,
  "flightTime": 0.55
}

### ─────────────────────────────────
### 2) 체력 측정 가능 날짜 목록 조회
### ─────────────────────────────────
GET {{base}}/measure-days
Authorization: {{accessToken}}

### ─────────────────────────────────
### 3) 체력 측정 조회 - 날짜별
### ─────────────────────────────────
GET {{base}}?measureDay=2025-11-02
Authorization: {{accessToken}}
